BiaBraga.Admin/Controllers/ProductsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BiaBraga.Domain.Models.Entitys;
using BiaBraga.Admin.Services;
using BiaBraga.Domain.Enums;
using BiaBraga.Repository.Interfaces;
using System.Linq;

namespace BiaBraga.Admin.Controllers
{
    [AuthService(Role.Administrador, Role.Supervisor)]
    public class ProductsController : Controller
    {
        private readonly IProductRepository _repository;

        public ProductsController(IProductRepository repository)
        {
            _repository = repository;
        }

        public async Task<IActionResult> Index(int? category, string name)
        {

            var categoriesSelectList = new SelectList(await _repository.GetAllAsync<Category>(), "Id", "Name");

            var products = await _repository.GetAllProductsAsync();

            if (category.HasValue)
            {
                products = products.Where(x => x.CategoryId == category.Value).ToList();

                var categorySelected = categoriesSelectList.FirstOrDefault(x => x.Value == category.Value.ToString());

                if (categorySelected != null)
                {
                    categorySelected.Selected = true;
                }
            }

            ViewData["CategoryId"] = categoriesSelectList;
            ViewData["Filtro"] = name;

            if (!string.IsNullOrEmpty(name))
            {
                products = products.Where(x => x.Name.ToUpper().Contains(name.ToUpper())).ToList();
            }

            return View(products);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var product = await _repository.GetProductByIdAsync(id.Value);
            if (product == null)
            {
                return RedirectToAction(nameof(Index));
            }

            product.Date = product.Date.ToLocalTime();

            return View(product);
        }

        public async Task<IActionResult> Create()
        {
            ViewData["CategoryId"] = new SelectList(await _repository.GetAllAsync<Category>(), "Id", "Name");
            return View();
        }

        private (decimal, decimal) FormatDecimalPrices(decimal price, decimal priceOld, bool save)
        {
            if (!save)
            {
                price = decimal.Round(price, 2, MidpointRounding.AwayFromZero);
                priceOld = decimal.Round(priceOld, 2, MidpointRounding.AwayFromZero);
            }
            else
            {
                var priceString = price.ToString();
                var priceOldString = priceOld.ToString();

                if(priceString == "0")
                {
                    priceString = "0000";
                }

                if (priceOldString == "0")
                {
                    priceOldString = "0000";
                }

                price = Convert.ToDecimal(priceString.Insert(priceString.Length - 2, "."), System.Globalization.CultureInfo.InvariantCulture);
                priceOld = Convert.ToDecimal(priceOldString.Insert(priceOldString.Length - 2, "."), System.Globalization.CultureInfo.InvariantCulture);
            }

            return (price, priceOld);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            if (ModelState.IsValid)
            {
                product.Date = DateTime.UtcNow;

                var decimals = FormatDecimalPrices(product.Price, product.OldPrice, true);

                product.Price = decimals.Item1;
                product.OldPrice = decimals.Item2;


                await _repository.AddAsync(product);
                return RedirectToAction(nameof(Details), new { id = product.ID });
            }
            ViewData["CategoryId"] = new SelectList(await _repository.GetAllAsync<Category>(), "Id", "Name", product.CategoryId);
            return View(product);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var product = await _repository.GetProductByIdAsync(id.Value);

            if (product == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var decimals = FormatDecimalPrices(product.Price, product.OldPrice, false);

            product.Price = decimals.Item1;
            product.OldPrice = decimals.Item2;

            ViewData["CategoryId"] = new SelectList(await _repository.GetAllAsync<Category>(), "Id", "Name", product.CategoryId);
            return View(product);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Product product)
        {
            if (id != product.ID)
            {
                return RedirectToAction(nameof(Index));
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var decimals = FormatDecimalPrices(product.Price, product.OldPrice, true);

                    product.Price = decimals.Item1;
                    product.OldPrice = decimals.Item2;


                    await _repository.UpdateAsync(product);
                }
                catch (Exception er)
                {

                }

                return RedirectToAction(nameof(Details), new { id = product.ID });
            }
            ViewData["CategoryId"] = new SelectList(await _repository.GetAllAsync<Category>(), "Id", "Name", product.CategoryId);
            return View(product);
        }

        [HttpPost, Route("Delete/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _repository.GetProductByIdAsync(id);

            await _repository.DeleteAsync(product);

            return RedirectToAction(nameof(Index));
        }
    }
}

BiaBraga.Admin/Controllers/UsersController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BiaBraga.Repository.Interfaces;
using BiaBraga.Domain.Models.Entitys;
using Microsoft.AspNetCore.Authorization;
using BiaBraga.Domain.Models;
using BiaBraga.Admin.Models.FormViewModel.Users;
using BiaBraga.Domain.Enums;
using System.Collections.Generic;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using System;
using Microsoft.AspNetCore.Authentication.Cookies;
using BiaBraga.Admin.Services;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using BiaBraga.Repository.Classes;
using BiaBraga.Business.Dtos;

namespace BiaBraga.Admin.Controllers
{
    [AuthService(Role.Administrador, Role.Supervisor)]
    [Route("users")]
    public class UsersController : Controller
    {
        private readonly IUserRepository _repository;

        public UsersController(IUserRepository repository)
        {
            _repository = repository;
        }

        [HttpGet]
        [Route("login")]
        [AllowAnonymous]
        public async Task<IActionResult> Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToRoute(new
                {
                    controller = "Home",
                    action = "Index"
                });
            }

            return View();
        }

        [HttpPost]
        [Route("login")]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginDto login)
        {
            if (ModelState.IsValid)
            {
                var result = await _repository.VerifyLoginAsync(login);

                if (result.HttpStatusCode == System.Net.HttpStatusCode.OK)
                {
                    var claims = new List<Claim>
                        {
                        new Claim(ClaimTypes.Name, result.Entity.Name),
                        new Claim(ClaimTypes.Role, result.Entity.Role.ToString()),
                        new Claim(ClaimTypes.Email, result.Entity.Email),
                    };

                    var identidadeDeUsuario = new ClaimsIdentity(claims, "Login");
                    ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(identidadeDeUsuario);

                    var propriedadeDeAutentificacao = new AuthenticationProperties
                    {
                        AllowRefresh = true,
                        ExpiresUtc = DateTime.Now.ToLocalTime().AddHours(2),
                        IsPersistent = true
                    };

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal, propriedadeDeAutentificacao);

                    return RedirectToRoute(new
                    {
                        controller = "Home",
                        action = "Index"
                    });
                }

                return View(new LoginViewModel
                {
                    Login = login,
                    ResultDefault = result
                });
            }

            return View(new LoginViewModel
            {
                Login = login,
                ResultDefault = new ResultDefault
                {
                    HttpStatusCode = System.Net.HttpStatusCode.Unauthorized,
                    Message = "Campos devem estar preenchidos"
                }
            });
        }

        // GET: Users
        public async Task<IActionResult> Index(string filtro)
        {
            var users = await _repository.GetAllUsersAsync();

            string filtroUpdate = filtro;
            if (!string.IsNullOrEmpty(filtroUpdate))
            {
                filtroUpdate = filtroUpdate.ToUpper().Trim();

                users = users.Where(x =>
                x.Name.ToUpper().Contains(filtroUpdate) ||

                (x.Nick != null && x.Nick.ToUpper().Contains(filtroUpdate)) ||

                x.Email.ToUpper().Contains(filtroUpdate) ||

                (x.CPF != null &&
                x.CPF.Replace(".", string.Empty).Replace("-", string.Empty).Replace("/", string.Empty)
                .Contains(filtroUpdate.Replace(".", string.Empty).Replace("-", string.Empty).Replace("/", string.Empty)))


                ).ToList();
            }

            ViewData["Filtro"] = filtro;

            return View(users);
        }

        [Route("Details/{id}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _repository.GetByIdAsync(id.Value);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [Route("Create")]
        public IActionResult Create()
        {
            return View();
        }

        [Route("Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Nick,AboutMe,Password,CPF,Birth,Telephone,CellPhone,Email,ReceiveCellPhoneMessage,ReceiveEmailMessage,Date,Role")] User user)
        {
            if (ModelState.IsValid)
            {
                await _repository.AddAsync(user);
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        [Route("Edit/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _repository.GetByIdAsync(id.Value);
            if (user == null)
            {
                return NotFound();
            }

            ViewData["GenerId"] = new SelectList(await _repository.GetAllAsync<Genre>(), "Id", "Name");

            return View(user);
        }
        [Route("Edit/{id}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Nick,AboutMe,Password,CPF,Birth,Telephone,CellPhone,Email,ReceiveCellPhoneMessage,ReceiveEmailMessage,Date,Role")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                user.Password = Encript.HashValue(user.Password);
                await _repository.UpdateAsync(user);

                return RedirectToAction(nameof(Index));
            }
            ViewData["GenerId"] = new SelectList(await _repository.GetAllAsync<Genre>(), "Id", "Name");
            return View(user);
        }

        [Route("Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _repository.GetByIdAsync(id.Value);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [Route("Delete")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _repository.GetByIdAsync(id);
            await _repository.DeleteAsync(user);
            return RedirectToAction(nameof(Index));
        }

        [Route("Logout")]
        [AllowAnonymous]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction(nameof(Login));
        }
    }
}

BiaBraga.Admin/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bia Braga Administrativo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="shortcut icon" href="~/house_hearth.ico">
</head>
<body>
    <header>
        @if (User.Identity.IsAuthenticated)
        {
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Administrativo </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            <li class="nav-item  dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Produtos
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item"
                                       asp-controller="Products"
                                       asp-action="Index"
                                       data-toggle="tooltip"
                                       data-placement="bottom"
                                       title="Gerenciamento sobre os produtos">Produtos</a>
                                    <a class="dropdown-item"
                                       asp-controller="Categories"
                                       asp-action="Index"
                                       data-toggle="tooltip"
                                       data-placement="bottom"
                                       title="Gerenciamento sobre as categorias dos produtos">Categorias</a>
                                    <a class="dropdown-item"
                                       asp-controller="Departments"
                                       asp-action="Index"
                                       data-toggle="tooltip"
                                       data-placement="bottom"
                                       title="Gerenciamento sobre os departamentos das categorias">Departamentos</a>
                                    <a class="dropdown-item"
                                       data-toggle="tooltip"
                                       data-placement="bottom"
                                       href="#"
                                       title="Gerenciamento sobre os produtos destaques">Destaques</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item"
                                       data-toggle="tooltip"
                                       data-placement="bottom"
                                       href="#"
                                       title="Relatório geral sobre os produtos mais vistos, vendidos e curtidos">Relatório</a>
                                    <a class="dropdown-item"
                                       data-toggle="tooltip"
                                       data-placement="bottom"
                                       href="#"
                                       title="Controle de estoque">Controle de estoque</a>
                                </div>
                            </li>

                            <li class="nav-item  dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Usuarios
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item"
                                       asp-controller="Users"
                                       asp-action="Index"
                                       data-toggle="tooltip"
                                       data-placement="bottom"
                                       title="Gerenciamento sobre os produtos">Usuarios</a>
                                    <a class="dropdown-item"
                                       href="#"
                                       data-toggle="tooltip"
                                       data-placement="bottom"
                                       title="Gerenciamento sobre as categorias dos produtos">Lista negra</a>
                                </div>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pedidos</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Monitoramento</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Tickets</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contatos</a>
                            </li>

                        </ul>
                    </div>
                    <a class="btn btn-light text-dark login-btn mt-1" asp-area="" asp-controller="Users" asp-action="Logout">
                    Sair &nbsp;
                        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-box-arrow-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z" />
                            <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z" />
                        </svg>
                    </a>
                </div>
            </nav>
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row text-center">
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="col-12">
                        <span>Usuario ativo: @User.Identity.Name - @User.FindFirstValue(ClaimTypes.Role)</span>
                    </div>
                }
                <div class="col">
                    &copy; @DateTime.Now.Year - Bia Braga Administrativo  - <a href="https://www.facebook.com.br/biabragacosmetics/" target="_blank">Bia Braga Cosmetics & SexShop</a>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

<style>
</style>